"""
ISO-3 country code to World Bank region mapping.
Regions: east_asia_pacific, europe_central_asia, latin_america_caribbean,
         middle_east_north_africa, north_america, south_asia, sub_saharan_africa
"""

REGION_MAP = {
    # East Asia & Pacific
    "ASM": "east_asia_pacific",
    "AUS": "east_asia_pacific",
    "BRN": "east_asia_pacific",
    "CHN": "east_asia_pacific",
    "FJI": "east_asia_pacific",
    "FSM": "east_asia_pacific",
    "GUM": "east_asia_pacific",
    "HKG": "east_asia_pacific",
    "IDN": "east_asia_pacific",
    "JPN": "east_asia_pacific",
    "KHM": "east_asia_pacific",
    "KIR": "east_asia_pacific",
    "KOR": "east_asia_pacific",
    "LAO": "east_asia_pacific",
    "MAC": "east_asia_pacific",
    "MHL": "east_asia_pacific",
    "MMR": "east_asia_pacific",
    "MNG": "east_asia_pacific",
    "MNP": "east_asia_pacific",
    "MYS": "east_asia_pacific",
    "NCL": "east_asia_pacific",
    "NRU": "east_asia_pacific",
    "NZL": "east_asia_pacific",
    "PHL": "east_asia_pacific",
    "PLW": "east_asia_pacific",
    "PNG": "east_asia_pacific",
    "PRK": "east_asia_pacific",
    "PYF": "east_asia_pacific",
    "SGP": "east_asia_pacific",
    "SLB": "east_asia_pacific",
    "THA": "east_asia_pacific",
    "TLS": "east_asia_pacific",
    "TON": "east_asia_pacific",
    "TUV": "east_asia_pacific",
    "TWN": "east_asia_pacific",
    "VNM": "east_asia_pacific",
    "VUT": "east_asia_pacific",
    "WSM": "east_asia_pacific",

    # Europe & Central Asia
    "ALB": "europe_central_asia",
    "AND": "europe_central_asia",
    "ARM": "europe_central_asia",
    "AUT": "europe_central_asia",
    "AZE": "europe_central_asia",
    "BEL": "europe_central_asia",
    "BGR": "europe_central_asia",
    "BIH": "europe_central_asia",
    "BLR": "europe_central_asia",
    "CHE": "europe_central_asia",
    "CHI": "europe_central_asia",
    "CYP": "europe_central_asia",
    "CZE": "europe_central_asia",
    "DEU": "europe_central_asia",
    "DNK": "europe_central_asia",
    "ESP": "europe_central_asia",
    "EST": "europe_central_asia",
    "FIN": "europe_central_asia",
    "FRA": "europe_central_asia",
    "FRO": "europe_central_asia",
    "GBR": "europe_central_asia",
    "GEO": "europe_central_asia",
    "GIB": "europe_central_asia",
    "GRC": "europe_central_asia",
    "GRL": "europe_central_asia",
    "HRV": "europe_central_asia",
    "HUN": "europe_central_asia",
    "IMN": "europe_central_asia",
    "IRL": "europe_central_asia",
    "ISL": "europe_central_asia",
    "ITA": "europe_central_asia",
    "KAZ": "europe_central_asia",
    "KGZ": "europe_central_asia",
    "LIE": "europe_central_asia",
    "LTU": "europe_central_asia",
    "LUX": "europe_central_asia",
    "LVA": "europe_central_asia",
    "MCO": "europe_central_asia",
    "MDA": "europe_central_asia",
    "MKD": "europe_central_asia",
    "MNE": "europe_central_asia",
    "NLD": "europe_central_asia",
    "NOR": "europe_central_asia",
    "POL": "europe_central_asia",
    "PRT": "europe_central_asia",
    "ROU": "europe_central_asia",
    "RUS": "europe_central_asia",
    "SMR": "europe_central_asia",
    "SRB": "europe_central_asia",
    "SVK": "europe_central_asia",
    "SVN": "europe_central_asia",
    "SWE": "europe_central_asia",
    "TJK": "europe_central_asia",
    "TKM": "europe_central_asia",
    "TUR": "europe_central_asia",
    "UKR": "europe_central_asia",
    "UZB": "europe_central_asia",
    "XKX": "europe_central_asia",

    # Latin America & Caribbean
    "ABW": "latin_america_caribbean",
    "ARG": "latin_america_caribbean",
    "ATG": "latin_america_caribbean",
    "BHS": "latin_america_caribbean",
    "BLZ": "latin_america_caribbean",
    "BOL": "latin_america_caribbean",
    "BRA": "latin_america_caribbean",
    "BRB": "latin_america_caribbean",
    "CHL": "latin_america_caribbean",
    "COL": "latin_america_caribbean",
    "CRI": "latin_america_caribbean",
    "CUB": "latin_america_caribbean",
    "CUW": "latin_america_caribbean",
    "CYM": "latin_america_caribbean",
    "DMA": "latin_america_caribbean",
    "DOM": "latin_america_caribbean",
    "ECU": "latin_america_caribbean",
    "GRD": "latin_america_caribbean",
    "GTM": "latin_america_caribbean",
    "GUY": "latin_america_caribbean",
    "HND": "latin_america_caribbean",
    "HTI": "latin_america_caribbean",
    "JAM": "latin_america_caribbean",
    "KNA": "latin_america_caribbean",
    "LCA": "latin_america_caribbean",
    "MEX": "latin_america_caribbean",
    "NIC": "latin_america_caribbean",
    "PAN": "latin_america_caribbean",
    "PER": "latin_america_caribbean",
    "PRY": "latin_america_caribbean",
    "PRI": "latin_america_caribbean",
    "SLV": "latin_america_caribbean",
    "SUR": "latin_america_caribbean",
    "SXM": "latin_america_caribbean",
    "TCA": "latin_america_caribbean",
    "TTO": "latin_america_caribbean",
    "URY": "latin_america_caribbean",
    "VCT": "latin_america_caribbean",
    "VEN": "latin_america_caribbean",
    "VGB": "latin_america_caribbean",
    "VIR": "latin_america_caribbean",

    # Middle East & North Africa
    "ARE": "middle_east_north_africa",
    "BHR": "middle_east_north_africa",
    "DJI": "middle_east_north_africa",
    "DZA": "middle_east_north_africa",
    "EGY": "middle_east_north_africa",
    "IRN": "middle_east_north_africa",
    "IRQ": "middle_east_north_africa",
    "ISR": "middle_east_north_africa",
    "JOR": "middle_east_north_africa",
    "KWT": "middle_east_north_africa",
    "LBN": "middle_east_north_africa",
    "LBY": "middle_east_north_africa",
    "MAR": "middle_east_north_africa",
    "MLT": "middle_east_north_africa",
    "OMN": "middle_east_north_africa",
    "PSE": "middle_east_north_africa",
    "QAT": "middle_east_north_africa",
    "SAU": "middle_east_north_africa",
    "SYR": "middle_east_north_africa",
    "TUN": "middle_east_north_africa",
    "YEM": "middle_east_north_africa",

    # North America
    "BMU": "north_america",
    "CAN": "north_america",
    "USA": "north_america",

    # South Asia
    "AFG": "south_asia",
    "BGD": "south_asia",
    "BTN": "south_asia",
    "IND": "south_asia",
    "LKA": "south_asia",
    "MDV": "south_asia",
    "NPL": "south_asia",
    "PAK": "south_asia",

    # Sub-Saharan Africa
    "AGO": "sub_saharan_africa",
    "BDI": "sub_saharan_africa",
    "BEN": "sub_saharan_africa",
    "BFA": "sub_saharan_africa",
    "BWA": "sub_saharan_africa",
    "CAF": "sub_saharan_africa",
    "CIV": "sub_saharan_africa",
    "CMR": "sub_saharan_africa",
    "COD": "sub_saharan_africa",
    "COG": "sub_saharan_africa",
    "COM": "sub_saharan_africa",
    "CPV": "sub_saharan_africa",
    "ERI": "sub_saharan_africa",
    "ETH": "sub_saharan_africa",
    "GAB": "sub_saharan_africa",
    "GHA": "sub_saharan_africa",
    "GIN": "sub_saharan_africa",
    "GMB": "sub_saharan_africa",
    "GNB": "sub_saharan_africa",
    "GNQ": "sub_saharan_africa",
    "KEN": "sub_saharan_africa",
    "LBR": "sub_saharan_africa",
    "LSO": "sub_saharan_africa",
    "MDG": "sub_saharan_africa",
    "MLI": "sub_saharan_africa",
    "MOZ": "sub_saharan_africa",
    "MRT": "sub_saharan_africa",
    "MUS": "sub_saharan_africa",
    "MWI": "sub_saharan_africa",
    "MYT": "sub_saharan_africa",
    "NAM": "sub_saharan_africa",
    "NER": "sub_saharan_africa",
    "NGA": "sub_saharan_africa",
    "REU": "sub_saharan_africa",
    "RWA": "sub_saharan_africa",
    "SDN": "sub_saharan_africa",
    "SEN": "sub_saharan_africa",
    "SHN": "sub_saharan_africa",
    "SLE": "sub_saharan_africa",
    "SOM": "sub_saharan_africa",
    "SSD": "sub_saharan_africa",
    "STP": "sub_saharan_africa",
    "SWZ": "sub_saharan_africa",
    "SYC": "sub_saharan_africa",
    "TCD": "sub_saharan_africa",
    "TGO": "sub_saharan_africa",
    "TZA": "sub_saharan_africa",
    "UGA": "sub_saharan_africa",
    "ZAF": "sub_saharan_africa",
    "ZMB": "sub_saharan_africa",
    "ZWE": "sub_saharan_africa",
}

# Short codes for regional aggregates in output
REGION_CODES = {
    "east_asia_pacific": "EAP",
    "europe_central_asia": "ECA",
    "latin_america_caribbean": "LAC",
    "middle_east_north_africa": "MENA",
    "north_america": "NAM",
    "south_asia": "SAS",
    "sub_saharan_africa": "SSA",
}

REGION_NAMES = {v: k for k, v in REGION_CODES.items()}


def get_region(iso3: str) -> str | None:
    return REGION_MAP.get(iso3.upper())


def get_region_code(region_name: str) -> str:
    return REGION_CODES.get(region_name, region_name)
