/**
 * Regenerates src/infrastructure/imaging/fonts.generated.ts from the .woff
 * sources. Satori needs the font bytes at runtime; embedding them as base64
 * keeps them out of Next's file-tracing guesswork, which is the usual reason a
 * satori render works locally and 500s on a serverless deploy.
 *
 *   node scripts/embed-fonts.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'src/infrastructure/imaging/fonts');

const SOURCES = [
  { constant: 'ANTON_400', file: 'anton-400.woff' },
  { constant: 'INTER_500', file: 'inter-500.woff' },
  { constant: 'INTER_700', file: 'inter-700.woff' },
];

const parts = SOURCES.map(({ constant, file }) => {
  const b64 = readFileSync(join(dir, file)).toString('base64');
  return `export const ${constant} =\n  '${b64}';`;
});

const banner = `// GENERATED by scripts/embed-fonts.mjs — do not edit.
// Source: src/infrastructure/imaging/fonts/*.woff (SIL Open Font License 1.1)
`;

writeFileSync(
  join(root, 'src/infrastructure/imaging/fonts.generated.ts'),
  `${banner}\n${parts.join('\n\n')}\n`
);

console.log(`embedded ${SOURCES.length} fonts`);
